# Generated by Django 4.0.4 on 2023-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gamereview_gamenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='photo',
            field=models.FileField(default='photo', upload_to='uploaded/images/'),
            preserve_default=False,
        ),
    ]
