# Generated by Django 4.0.4 on 2023-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_gamenews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
